version: "3.5"
services:
  configrd:
    build:
      context: .
      dockerfile: Dockerfile
    image: configrd/configrd-service
    container_name: configrd-service
    environment:
       - CONFIG_URI=file:/srv/configrd/repo-defaults.yml
       - PORT=9191
       - STREAMSOURCE=file
       - LOG_LEVEL=INFO
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:${PORT:-9191}:${PORT:-9191}"
    volumes:
      - /srv/configrd:/srv/configrd